166266848 Deploy app to heroku
andela/wger-space pull request #4
Opened 2019-05-30 20:02 UTC by sebbss

#### What does this PR do?

Deploy the app on heroku

#### Description of Task to be completed?

- created a Procfile to specify the commands executed by the app on startup
- created an app.json file that  manifests a format for describing web apps

#### How should this be manually tested?

- follow the link to the deployed app `https://wger-space.herokuapp.com/en/software/features`

#### What are the relevant pivotal tracker stories?

[#166266848](https://www.pivotaltracker.com/story/show/166266848)

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/44563961/58660809-fbef2980-832e-11e9-89d0-2c56744f0db6.png)

2019-05-31 07:53 UTC, richien requested changes
Hi @sebbss, first of all, thanks for finally getting the app to deploy. I was wondering, is this the final display or are you working on fixing the issues with rendering CSS and JS in the site?

2019-05-31 13:18 UTC, NicholusMuwonge requested changes
@sebbss this Took you some hard work, I thank you for your effort, The application link works fine on my end, though I was wondering If you were supposed to create two links for both production and staging?

2019-05-31 14:24 UTC, frankopkusianwar commented
> @sebbss this Took you some hard work, I thank you for your effort, The application link works fine on my end, though I was wondering If you were supposed to create two links for both production and staging?

@NicholusMuwonge I think @sebbss should add the capability to use review apps such that temporary deployment links are created whenever a PR is created

2019-06-05 08:59 UTC, nakatuddesuzan commented on app.json
> +  }
Hey @sebbss , kindly add a line below here

2019-06-05 08:59 UTC, nakatuddesuzan commented on wger/settings_global.py
> +# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
Here too

2019-06-05 09:12 UTC, richien approved these changes

2019-06-05 09:28 UTC, nakatuddesuzan commented
> @sebbss this Took you some hard work, I thank you for your effort, The application link works fine on my end, though I was wondering If you were supposed to create two links for both production and staging?

Lets do staging for the mean time

2019-06-05 09:33 UTC, nakatuddesuzan approved these changes

2019-06-05 09:33 UTC, merged

2019-06-05 09:33 UTC, NicholusMuwonge approved these changes